### ISSUE TITLE
Open ./receiver1 1

### ISSUE THREAD

**Issue by romanremus** [sq5bpf/telive#34]
hello everyone, I recently reinstalled linux mint, gnuradio companion 3.10, and I can no longer open ./receiver1 1, it is not compatible with gnuradio 3.10, is there another method to open this receiver in gnuradio 3.10? thank you
the receiver is in the folder cd ~/tetra/osmo-tetra-sq5bpf/src
./receiver1 1

**Comment by romanremus** [comment]
Hello everyone, how can I register tetra traffic, voice + data, from receiver1udp 1?

**Comment by sq5bpf** [comment]
The receiver1udp script in osmo-tetra-sq5bpf has support for gnuradio 3.10
Don't use receiver1

**Comment by sq5bpf** [comment]
Also you will find new flowgraphs for gnuradio 3.10 in telive gnuradio-companion/python3_based_gnuradio

There is no documentation for them so far, but they will work in a similar way to the earlier flowgraphs (apart from gnuradio QT gui deficiencies, which unfortunately will have to be fixed by the gnuradio maintainers)
